// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCGgZb20i3WpNKGu19OITjyvxrs2vdjZsk',
    appId: '1:615305343035:web:a7e668857eb2318093ac1e',
    messagingSenderId: '615305343035',
    projectId: 'insta-app-a62e6',
    authDomain: 'insta-app-a62e6.firebaseapp.com',
    storageBucket: 'insta-app-a62e6.appspot.com',
    measurementId: 'G-VX4DD64XKP',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDYFx1UIjRweJ1vK86xpcz0ntjgRt7TFD0',
    appId: '1:615305343035:android:f9c9a2d7cf7c2d9593ac1e',
    messagingSenderId: '615305343035',
    projectId: 'insta-app-a62e6',
    storageBucket: 'insta-app-a62e6.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCURPEP5P2Hlp6SkzbEG34-ciG49j6s7JA',
    appId: '1:615305343035:ios:39e7e52564eea8db93ac1e',
    messagingSenderId: '615305343035',
    projectId: 'insta-app-a62e6',
    storageBucket: 'insta-app-a62e6.appspot.com',
    iosBundleId: 'com.example.instaApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCURPEP5P2Hlp6SkzbEG34-ciG49j6s7JA',
    appId: '1:615305343035:ios:39e7e52564eea8db93ac1e',
    messagingSenderId: '615305343035',
    projectId: 'insta-app-a62e6',
    storageBucket: 'insta-app-a62e6.appspot.com',
    iosBundleId: 'com.example.instaApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCGgZb20i3WpNKGu19OITjyvxrs2vdjZsk',
    appId: '1:615305343035:web:f22c054c47801b3593ac1e',
    messagingSenderId: '615305343035',
    projectId: 'insta-app-a62e6',
    authDomain: 'insta-app-a62e6.firebaseapp.com',
    storageBucket: 'insta-app-a62e6.appspot.com',
    measurementId: 'G-QWJTWZ179S',
  );
}
